const inquirer = require('inquirer')
const fs = require('fs')
const Employee = require('Employee')
const Engineer = require('Engineer')
const Intern = require('Intern')
const Manager = require('Manager')